apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-prod-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ruchabhange/Inception-argo-demo.git
    targetRevision: HEAD
    path: ./java-sample-application/kustomize-manifest/overlays/prod
   
  destination:
    server: https://kubernetes.default.svc
    namespace: java-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
